In [1]:
import pandas as pd

In [2]:
!pwd

/home/jpelletier/code/DaveGiGi/Duckstradamus/notebooks

In [3]:
!ls

at_eda.ipynb  David  jacques_data  jacques_notebook.ipynb

In [4]:
df = pd.read_csv("jacques_data/199708_Generation_MD.csv")

In [13]:
df2 = pd.read_csv("jacques_data/202604_Generation_MD.csv")

In [16]:
!pwd

/home/jpelletier/code/DaveGiGi/Duckstradamus/notebooks

In [17]:
df3 = pd.read_csv("jacques_data/Demand_trends_20260518215015.csv")

In [5]:
df.head()

,Site_Code,POC_Code,Nwk_Code,Gen_Code,Fuel_Code,Tech_Code,Trading_date,TP1,TP2,TP3,...,TP41,TP42,TP43,TP44,TP45,TP46,TP47,TP48,TP49,TP50
0,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,1997-08-01,29230,29100,29470,...,33790,30310,27580,27110,27200,27310,27330,27260,NaN,NaN
1,ARG,ARG1101,TRUS,argyle_wairau,Hydro,Hydro,1997-08-01,0,0,0,...,3892,908,6,0,0,0,0,0,NaN,NaN
2,ARI,ARI1101,MRPL,arapuni,Hydro,Hydro,1997-08-01,81510,81330,64800,...,76160,72360,63180,62640,62310,63050,63130,54020,NaN,NaN
3,ATI,ATI2201,MRPL,atiamuri,Hydro,Hydro,1997-08-01,19200,15270,15030,...,29350,29650,29670,23190,19910,17830,17930,17550,NaN,NaN
4,AVI,AVI2201,MERI,aviemore,Hydro,Hydro,1997-08-01,87970,87880,87770,...,67190,53040,45970,47080,50350,50870,51740,52350,NaN,NaN

In [14]:
df2.head()

,Site_Code,POC_Code,Nwk_Code,Gen_Code,Fuel_Code,Tech_Code,Trading_Date,TP1,TP2,TP3,...,TP41,TP42,TP43,TP44,TP45,TP46,TP47,TP48,TP49,TP50
0,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,2026-04-01,9040,12580,12710,...,21620,21630,21740,22090,22170,22190,22180,20940,NaN,NaN
1,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,2026-04-02,18660,18680,18250,...,17050,22150,21950,22210,22310,22210,21220,12970,NaN,NaN
2,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,2026-04-03,12870,12880,12890,...,10120,11290,11370,11270,11350,11310,11350,11320,NaN,NaN
3,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,2026-04-04,11340,12340,12320,...,22170,22190,22180,20700,12650,12300,12330,12290,NaN,NaN
4,ARA,ARA2201,MRPL,aratiatia,Hydro,Hydro,2026-04-05,12310,12300,12310,...,14280,11870,11800,9350,7900,7840,7840,7830,7950.0,7880.0

In [18]:
df3.head()

,Period start,Period end,Region ID,Region,Demand (GWh),Demand ($)
0,01/01/2021 00:00:00,01/01/2021 00:30:00,UNI,Upper North Island,0.471,59062.08
1,01/01/2021 00:00:00,01/01/2021 00:30:00,CNI,Central North Island,0.345,41358.44
2,01/01/2021 00:00:00,01/01/2021 00:30:00,LNI,Lower North Island,0.215,26436.13
3,01/01/2021 00:00:00,01/01/2021 00:30:00,USI,Upper South Island,0.242,31635.12
4,01/01/2021 00:00:00,01/01/2021 00:30:00,LSI,Lower South Island,0.461,59128.30

In [6]:
df.shape

(1333, 57)

In [7]:
df.columns

Index(['Site_Code', 'POC_Code', 'Nwk_Code', 'Gen_Code', 'Fuel_Code',
       'Tech_Code', 'Trading_date', 'TP1', 'TP2', 'TP3', 'TP4', 'TP5', 'TP6',
       'TP7', 'TP8', 'TP9', 'TP10', 'TP11', 'TP12', 'TP13', 'TP14', 'TP15',
       'TP16', 'TP17', 'TP18', 'TP19', 'TP20', 'TP21', 'TP22', 'TP23', 'TP24',
       'TP25', 'TP26', 'TP27', 'TP28', 'TP29', 'TP30', 'TP31', 'TP32', 'TP33',
       'TP34', 'TP35', 'TP36', 'TP37', 'TP38', 'TP39', 'TP40', 'TP41', 'TP42',
       'TP43', 'TP44', 'TP45', 'TP46', 'TP47', 'TP48', 'TP49', 'TP50'],
      dtype='object')

In [8]:
df["Site_Code"].unique()

array(['ARA', 'ARG', 'ARI', 'ATI', 'AVI', 'BEN', 'BWK', 'COB', 'COL',
       'CYD', 'HLY', 'HWA', 'KIN', 'KPO', 'MAN', 'MAT', 'MHO', 'MTI',
       'NPL', 'OHA', 'OHB', 'OHC', 'OHK', 'OKI', 'OTA', 'PPI', 'ROT',
       'ROX', 'RPO', 'SFD', 'SWN', 'TKA', 'TKB', 'TKU', 'TMU', 'TUI',
       'WHI', 'WKM', 'WPA', 'WRK', 'WTK'], dtype=object)

In [9]:
df["Fuel_Code"].unique()

array(['Hydro', 'Coal', 'Wood', 'Gas&Oil', 'Geo', 'Gas', 'Diesel'],
      dtype=object)

In [10]:
df["Tech_Code"].unique()

array(['Hydro', 'Thrml', 'Cogen', 'Geo'], dtype=object)

In [11]:
df["Gen_Code"].nunique()

41

In [12]:
df["Trading_date"].max()

'1997-08-31'